import * as React from "react";

export const FORM_OPTIONS = {
  heightFeet: ["4", "5", "6", "7"],
  heightInches: [
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
  ],
  citizenship: ["Yes", "No"],
  unit: ["Inches", "Millimeters"],
  regulated: ["Yes", "No"],
  genders: ["Male", "Female", "Nonbinary / Unspecified"],
  eyeColors: [
    "BLACK",
    "BLUE",
    "BROWN",
    "GRAY",
    "GREEN",
    "HAZEL",
    "MAROON",
    "MULTICOLOR",
    "PINK",
    "UNKNOWN",
  ],
  hairColors: [
    "BALD",
    "BLACK",
    "BLONDE",
    "BLUE",
    "BROWN",
    "GRAY",
    "GREEN",
    "ORANGE",
    "PINK",
    "PURPLE",
    "RED",
    "SANDY",
    "UNKNOWN",
    "WHITE",
  ],
  idTypes: ["California DL", "California ID", "DEPT OF DEFENSE ID"],
  waitingPeriodExemption: [
    "CFD NUMBER",
    "COLLECTOR",
    "PEACE OFFICER (LETTER REQUIRED)",
    "SPECIAL WEAPONS PERMIT",
  ],
  nonRosterExemption: [
    "Department of Justice",
    "Police Department",
    "Sheriff's Office",
    "Marshal's Office",
    "Department of Corrections and Rehabilitation",
    "Department of the California Highway Patrol",
    "Any District Attorney's Office",
    "Any Federal Law Enforcement Agency",
    "Military or Naval Forces of the State or the United States",
    "The Department of Parks and Recreation",
    "Department of Alcoholic Beverage Control",
    "Division of Investigation of the Department of Consumer Affairs",
    "Department of Motor Vehicles",
    "Fraud Division of the Department of Insurance",
    "State Department of State Hospitals",
    "Department of Fish and Wildlife",
    "State Department of Developmental Services",
    "Department of Forestry and Fire Protection",
    "A County Probation Department",
    "The Los Angeles World Airports",
    "K-12 Public School District use by a School Police Officer",
    "A Municipal Water District for use by a Park Ranger",
    "A County for use by a Welfare Fraud Investigator or Inspector",
    "A County for use by the Coroner or the Deputy Coroner",
    "The Supreme Court and the Courts of Appeal",
    "A Fire Department or Fire Protection Agency",
    "The University of California/California State University Police Department",
    "A California Community College Police Department",
    "A Harbor or Port District or other entity",
    "None",
    "Department of Cannabis Control",
    "A local Agency employing Park Rangers",
  ],
  category: [
    "4 OR MORE BARRELS",
    "BOLT ACTION",
    "DERRINGER",
    "DOUBLE BARREL",
    "LEVER ACTION",
    "OVER AND UNDER",
    "REVOLVER",
    "SEMI-AUTOMATIC",
    "SINGLE SHOT",
    "THREE BARRELS",
  ],
  calibers: [
    ".14 Walker Hornet, .14/221, .14-222, 14-gauge shotgun",
    ".17 (various)",
    ".204 Ruger, Remington, Savage",
    ".218 Bee",
    ".22 Short/Long/Rifle rim. cart.; .22 Hornet, .22-250, 22-gauge",
    ".220 Swift",
    ".221 Remington Fireball",
    ".222 Remington, .222 Remington Magnum",
    ".223 Remington",
    ".224 Weatherby Mag, .224 Valkyrie",
    ".225 Winchester",
    ".226 JDJ",
    ".240 Weatherby Mag",
    ".243 Winchester",
    ".25 ACP, .25-06, .25-20, .25-35",
    ".250-3000 Savage",
    ".256 Newton, .256 Win Mag",
    ".257 Roberts, .257 Weatherby Mag, .257 Mini Dreadnaught",
    ".26 Nosler",
    ".260 Mag. Res Lone Eagle, .260 Rem, .260 Savage, .260 Thompson/Cen",
    ".264 Winchester Magnum",
    ".270 Winchester, .270 Weatherby Magnum",
    ".276 Enfield, .276 Pederson",
    ".28 Nosler, 28-gauge shotgun",
    ".280 Remington, .280 JDJ, .80 British",
    ".284 Winchester",
    ".30 M1 Carbine, .30-40 Krag, 30-30 Winchester, .30 Mauser",
    ".30-06 U.S. (.30 Springfield)",
    ".300 Win. Mag/.300 Wtherby Mag/.300 Sav/.300 H&H Mag/.300 AAC Blkout",
    ".303 British, .303 Savage",
    ".307 Winchester",
    ".308 Winchester",
    ".309 JDJ",
    ".31 Baby Dragoon 1848, 1849 Pocket",
    ".32 ACP,.32 Short Colt, .32 Long Colt, .32 H&R Mag, 32-gauge shotgun",
    ".32-20 Winchester",
    ".32-40 Winchester",
    ".320 Revolver",
    ".325 Winchester",
    ".327 Federal Magnum Cartridge",
    ".33 Winchester",
    ".330 Dakota",
    ".338 Winchester Mag, .338 Federal, .338 Lapua Mag",
    ".340 Weatherby Magnum",
    ".348 Winchester",
    ".35 Whelen, .35 Remington, .350 Remington Mag, .35 S&W",
    ".35-06 JDJ",
    ".350 Legend",
    ".351 Winchester",
    ".356 Win, SW940",
    ".357 Remington Magnum, .357 Maximum, .357 AutoMag, .357 Sig",
    ".358 Win, Remington, RPM, ROP, STA",
    ".36 caliber markings normally found only on black-powder firearms",
    ".375 H&H Magnum, .375 Winchester, 375-06 JDJ",
    ".376 Steyr",
    ".378 Weatherby Mag",
    ".38 S&W, .38 (S&W) Special, .38 ACP, .38 Super, etc.",
    ".38-40 Winchester",
    ".38-55 Win, .38-55 Ballard",
    ".380 ACP in U.S.; also known as 9mm Kurz/Corto/Short",
    ".40 S&W",
    ".40-44 Woodswalker",
    ".40-65 Winchester",
    ".400 Cor-bon",
    ".401 Winchester, .401 Power Mag",
    ".404 Jeffery",
    ".405 Winchester",
    ".408 Cheytac",
    ".41 Short Rimfire, .41 Remington Mag, .41 Action Express, .41 AutoMa",
    ".411 JDJ",
    ".416 Barrett, .416 Rigby, .416 Rem Mag",
    ".425 Express",
    ".44 Russian, .44 Special, .44 Rem. Mag, .44 AutoMag",
    ".44-40 Winchester",
    ".440 Cor-bon",
    ".444 Marlin",
    ".445",
    ".45 ACP, .45 AutoRim, .45 Short/Long Colt, .45 Winchester Mag",
    ".45-70 U.S. Government",
    ".450 Marlin, .450 Dakota, .450 Revolver, .450 Bushmaster",
    ".454 Casull-ragin Bull Model with Colt 45",
    ".455 Webley, or .455 Manstopper, .455 Enfield",
    ".458 Winchester Mag, .458 Whisper",
    ".460 Weatherby Mag, .460 A-Square, .460 S&W, .460 Steyr",
    ".470 Nitro Express, .470 Rigby",
    ".475 Linebaugh, .475 JDJ",
    ".476 Enfield",
    ".480 Ruger",
    ".485 British",
    ".495 A-Square",
    ".50 BMG, .50 Action Exp, .50 Beowolf; black-powder firearm",
    ".50-70 Gov't",
    ".500 Linebaugh, .500 S&W Mag, .500 WE",
    ".510 DTC",
    ".54 Used in black-powder firearms",
    ".577 Tyrannosaur, .577/450 Martini Henry, .577 Snyder",
    ".58 Used in black-powder firearms; .577 Nitro Express Elephant Gun",
    ".60 Used in black-powder firearms; .600 Nitro Express Elephant Gun",
    ".653 Scramjet",
    ".671 Phantom, .671 Blackbrid",
    ".75 caliber, 7.5mm Nagant (Swedish), 7.5mm Swiss, 7.5mm French MAS",
    ".909 Eagle",
    ".953 Hellcat, .953 Saturn",
    "10.15mm Jermann, 10.15mm Serbian Mauser",
    "10.4mm Italian, 10.4mm Swiss",
    "10.57 Maverick, 10.57 Meteor",
    "10.75mm Russian Berdan",
    "10mm, 10-gauge shotgun",
    "11.15mm Spanish Rem., 11.15mm Mauser, 11.15mm Werndl M/77",
    "11.43mm Egyptian, 11.43mm Turkish",
    "11.4mm Brazilian, 11.4mm Werndel M/73",
    "11.75mm Montenegrin",
    "11.7mm Danish Rem.",
    "11mm Mauser, 11mm French, 11 Belgian",
    "12-gauge shotgun",
    "12.5mm",
    "13mm Gyrojet rocket pistol/carbine",
    "16-gauge shotgun",
    "2.7mm Kolibri",
    "20-gauge shotgun",
    "24-gauge shotgun",
    "3mm Kolibri",
    "4-gauge shotgun or blank",
    "410-gauge shotgun",
    "5.45x39mm, 5.45x18mm Soviet",
    "5.56x45mm NATO",
    "5.5mm Velo Dog",
    "5.6x50mm Mag, 5.6x57mm RWS, 5.6x61mm, 5.6x52 Rmm",
    "5.7 X 28mm Fabrique Nationale",
    "5mm Bergmann, 5mm Clement Auto",
    "6.17 Spitfire, 6.17 Flash",
    "6.35mm",
    "6.5mm (various); .65 caliber black-powder firearms",
    "6.8mm Remington, 6.8x57mm Chinese",
    "6mm Remington, 6mm SAW",
    "7-30 Waters",
    "7.21 Tomahawk, 7.21 Firehawk, 7.21 Firebird",
    "7.35mm Carcano",
    "7.62x39 Soviet, 7.62x51 NATO, 7.62x54R Rus. Moisin-Nagant, 7.62x35",
    "7.63mm Mannlicher, 7.62x25mm Tokarev",
    "7.65mm Luger, 7.65mm Roth-Sauer, 7.65 MAS (French), .30 Luger",
    "7.7mm Arisaka",
    "7.82 Patriot, 7.82 Warbird",
    "7.92mm Kurz (Short)",
    "7mm, Rem Weatherby Mag, 7mm Bench Rest, 7x57 Mauser, 7mm-08 Rem",
    "8.59 Galaxy, 8.59 Titan",
    "8x57 Mauser, 8mm Lebel, 8mm Remington Mag, 8x56mmR, 8-gauge shotgun",
    "9.3mm JDJ, 9.3x57mm Mauser",
    "9.5mm Turkish Mauser",
    "9.8mm Auto Colt",
    "9mm L/Para/9x18,9x21,9x23/Largo 9x19, 9mm rimfire shotgun",
    "Firearm with interchangable barrels",
  ],
  makes: [
    "ARMSCOR PRECISION",
    "BERETTA",
    "BERSA",
    "BROWNING",
    "CAMDON DEFENSE",
    "CENTURY ARMS INC",
    "CHARTER 2000",
    "COLT",
    "CTF MANUFACTURING",
    "CZ USA",
    "DAN WESSON",
    "EUROPEAN AMERICAN ARMORY CORP",
    "FMK FIREARMS",
    "FN HERSTAL, S.A.",
    "FRANKLIN ARMORY",
    "GERMAN SPORTS GUN",
    "GIRSAN (IMPORTED BY EAA CORP)",
    "GLOCK",
    "GUNCRAFTER INDUSTRIES, LLC",
    "HECKLER & KOCH",
    "HENRY REPEATING ARM",
    "JUGGERNAUT TACTICAL",
    "KAHR ARMS",
    "KIMBER",
    "LES BAE",
    "MAGNUM RESEARCH",
    "NIGHTHAWK CUSTOM",
    "NORTH AMERICAN ARMS",
    "PHOENIX ARMS",
    "ROST MARTIN",
    "SECOND AMENDMENT ZONE",
    "SEECAMP",
    "SIG SAUER",
    "SMITH & WESSON",
    "SPRINGFIELD ARMORY",
    "STANDARD MANUFACTURING CO",
    "STRAYER VOIGT",
    "STURM, RUGER & CO",
    "TAURUS",
    "VALTRO",
    "WALTHER",
    "WILSON COMBAT",
  ],
  restrictionsExemptions: [
    "COLLECTOR - 03 FFL - VALID COE",
    "COMMUNITY COLLEGE - POST CERTIFIED",
    "DULY AUTHORIZED LAW ENFORCEMENT AGENCY",
    "ENTERTAINMENT COMPANY - PERMIT - VALID COE",
    "EXCHANGE - WITHIN PRECEDING 30 DAYS",
    "LAW ENFORCEMENT AGENCY - CALIFORNIA",
    "LICENSED CALIFORNIA FIREARMS DEALER",
    "PEACE OFFICER - ACTIVE - LETTER REQUIRED",
    "PEACE OFFICER - CALIFORNIA - ACTIVE",
    "PRIVATE SECURITY COMPANY (PPO) - CALIFORNIA - LICENSED",
    "REPLACEMENT - REPORTED LOST OR STOLEN FIREARM",
    "SPECIAL WEAPONS PERMIT",
    "STATE OR LOCAL CORRECTIONAL FACILITY",
  ],
  race: [
    "AMERICAN INDIAN",
    "ASIAN INDIAN",
    "BLACK",
    "CAMBODIAN",
    "CHINESE",
    "FILIPINO",
    "GUAMANIAN",
    "HAWAIIAN",
    "HISPANIC",
    "JAPANESE",
    "KOREAN",
    "LAOTIAN",
    "OTHER",
    "OTHER ASIAN",
    "PACIFIC ISLANDER",
    "SAMOAN",
    "VIETNAMESE",
    "UNKNOWN",
    "WHITE",
  ],
  fsd: [
    "ANTIQUE",
    "APPROVED LOCK BOX",
    "FSD PURCHASED",
    "OEM",
    "SAFE AFFIDAVIT",
  ],
  colors: [
    "ALUMINUM/SILVER",
    "BEIGE",
    "BLACK",
    "BLUE",
    "BLUE, DARK",
    "BLUE, LIGHT",
    "BRONZE",
    "BROWN",
    "BURGUNDY/MAROON",
    "CAMOUFLAGE",
    "CHROME/STAINLESS",
    "COPPER",
    "CREAM/IVORY",
    "GOLD",
    "GRAY",
    "GREEN",
    "GREEN, DARK",
    "GREEN, LIGHT",
    "LAVENDER",
    "ORANGE",
    "OTHER, MULTICOLOR",
    "PINK",
    "PURPLE",
    "RED",
    "TAN",
    "TURQUOISE",
    "UNKNOWN",
    "WHITE",
    "YELLOW",
  ],
  exemptionCodes: [
    "X01 SPECIAL WEAPONS PERMIT",
    "X02 OPERATION OF LAW REPRESENTATIVE",
    "X03 FIREARM BEING RETURNED TO OWNER",
    "X13 FFL COLLECTOR W/COE CURIO/RELIC TRANSACTION",
    "X21 MILITARY - ACTIVE DUTY",
    "X22 MILITARY - ACTIVE RESERVE",
    "X25 MILITARY - HONORABLY RETIRED",
    "X31 PEACE OFFICER - CALIFORNIA - ACTIVE",
    "X32 PEACE OFFICER - FEDERAL - ACTIVE",
    "X33 PEACE OFFICER - HONORABLY RETIRED",
    "X34 PEACE OFFICER - RESERVE",
    "X35 PEACE OFFICER - FEDERAL - HONORABLY RETIRED",
    "X41 CARRY CONCEALED WEAPON (CCW) PERMIT HOLDER",
    "X81 PEACE OFFICER STANDARDS AND TRAINING (832PC) FIREARMS TRAINING",
    "X91 PARTICULAR AND LIMITED AUTHORITY PEACE OFFICERS",
    "X95 LAW ENFORECEMENT SERVICE GUN TO FAMILY MEMBER",
    "X96 TRANSACTION IS TO REPLACE A BROKEN OR DEFECTIVE HANDGUN FRAME",
    "X99 DOJ CERTIFIED INSTRUCTOR",
  ],
  placesOfBirth: [
    "AFGHANISTAN",
    "AGUASCALIENTES",
    "ALABAMA",
    "ALASKA",
    "ALBANIA",
    "ALBERTA",
    "ALGERIA",
    "AMERICAN SAMOA ISLANDS",
    "ANDORRA",
    "ANGOLA",
    "ANGUILLA",
    "ANTIGUA",
    "ARGENTINA",
    "ARIZONA",
    "ARKANSAS",
    "ARMENIA",
    "ARUBA",
    "ASHMORE AND CARTIER ISLANDS",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "AZORES ISLANDS",
    "BAHAMAS",
    "BAHRAIN",
    "BAJA CALIFORNIA NORTE",
    "BAJA CALIFORNIA SUR",
    "BAKER ISLAND",
    "BALEARIC ISLANDS",
    "BANGLADESH",
    "BARBADOS",
    "BASSAS DA INDIA",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BERMUDA",
    "BHUTAN",
    "BOLIVIA",
    "BOSNIA HERCEGOVENA",
    "BOTSWANA",
    "BOUVET ISLAND",
    "BRAZIL",
    "BRITISH COLUMBIA",
    "BRITISH INDIAN OCEAN TERR",
    "BRITISH VIRGIN ISLANDS",
    "BRUNEI",
    "BULGARIA",
    "BURKINA FASO",
    "BURMA",
    "BURUNDI",
    "BYELARUS",
    "CALIFORNIA",
    "CAMBODIA (KHMER AND KAMPUCHEA)",
    "CAMEROON",
    "CAMPECHE",
    "CANADA",
    "CANAL ZONE",
    "CANARY ISLANDS",
    "CAPE VERDE ISLANDS",
    "CAROLINE ISLANDS",
    "CAYMAN ISLANDS",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "CHIAPAS",
    "CHIHUAHUA",
    "CHILE",
    "CHRISTMAS ISLAND",
    "CLIPPERTON ISLAND",
    "COAHUILA",
    "COCOS (KEELING) ISLANDS",
    "COLIMA",
    "COLOMBIA",
    "COLORADO",
    "COMOROS ISLANDS",
    "CONNECTICUT",
    "COOK ISLANDS",
    "CORAL SEA ISLANDS",
    "COSTA RICA",
    "CROATIA",
    "CUBA",
    "CYPRUS",
    "CZECH REPUBLIC",
    "DELAWARE",
    "DENMARK",
    "DISTRICT OF COLUMBIA",
    "DISTRITO FEDERAL",
    "DJIBOUTI",
    "DOMINICA",
    "DOMINICAN REPUBLIC",
    "DURANGO",
    "EAST GERMANY",
    "ECUADOR",
    "EGYPT",
    "EL SALVADOR",
    "ENGLAND",
    "EQUATORIAL GUINEA",
    "ERETRIA",
    "ESTONIA",
    "ETHIOPIA",
    "EUROPA ISLAND",
    "FALKLAND ISLANDS",
    "FAROE ISLANDS",
    "FEDERATED STATES OF MICRONESIA",
    "FIJI",
    "FINLAND",
    "FLORIDA",
    "FRANCE",
    "FRENCH GUIANA",
    "FRENCH POLYNESIA",
    "FRENCH SOUTHERN AND ANTARTIC LANDS",
    "GABON",
    "GAMBIA",
    "GAZA",
    "GEORGIA (COUNTRY)",
    "GEORGIA (STATE)",
    "GERMANY",
    "GHANA",
    "GIBRALTAR",
    "GREECE",
    "GREENLAND",
    "GRENADA",
    "GUADELOUPE",
    "GUAM",
    "GUANAJUATO",
    "GUATEMALA",
    "GUERNSEY",
    "GUERRERO",
    "GUINEA",
    "GUINEA/BISSAU",
    "GUYANA",
    "HAITI",
    "HAWAII",
    "HEARD ISLAND & MCDONALD ISLAND",
    "HIDALGO",
    "HONDURAS",
    "HONG KONG",
    "HOWLAND ISLAND",
    "HUNGARY",
    "ICELAND",
    "IDAHO",
    "ILLINOIS",
    "INDIA",
    "INDIANA",
    "INDONESIA",
    "IOWA",
    "IRAN",
    "IRAQ",
    "IRELAND (NOT NORTHERN IRELAND)",
    "ISLE OF MAN",
    "ISRAEL",
    "ITALY",
    "IVORY COAST",
    "JALISCO",
    "JAMAICA",
    "JAN MAYEN",
    "JAPAN",
    "JARVIS ISLAND",
    "JERSEY",
    "JOHNSTON ISLANDS",
    "JORDAN",
    "JUAN DE NOVA ISLAND",
    "KANSAS",
    "KAZAKHSTAN",
    "KENTUCKY",
    "KENYA",
    "KINGMAN REEF",
    "KIRIBATI",
    "KOSOVO",
    "KUWAIT",
    "KYRGYZSTAN",
    "LAOS",
    "LATVIA",
    "LEBANON",
    "LESOTHO",
    "LIBERIA",
    "LIBYA",
    "LIECHTENSTEIN",
    "LITHUANIA",
    "LOUISIANA",
    "LUXEMBOURG",
    "MACAU",
    "MADEIRA ISLANDS",
    "MAINE",
    "MALAGASY REPUBLIC",
    "MALAWI",
    "MALAYSIA",
    "MALDIVES",
    "MALI",
    "MALTA",
    "MANAHIKI ISLAND",
    "MANITOBA",
    "MARIANA ISLANDS",
    "MARSHALL ISLANDS",
    "MARTINIQUE",
    "MARYLAND",
    "MASSACHUSETTS",
    "MAURITANIA",
    "MAURITIUS",
    "MAYOTTE",
    "MEXICO",
    "MICHIGAN",
    "MICHOACAN",
    "MIDWAY ISLANDS",
    "MINNESOTA",
    "MISSISSIPPI",
    "MISSOURI",
    "MOLDOVA",
    "MONACO",
    "MONGOLIA",
    "MONTANA",
    "MONTSERRAT",
    "MORELOS",
    "MOROCCO",
    "MOZAMBIQUE",
    "NAMIBIA/SOUTHWEST AFRICA",
    "NAURU",
    "NAVASSA ISLAND",
    "NAYARIT",
    "NEBRASKA",
    "NEPAL",
    "NETHERLANDS",
    "NETHERLANDS ANTILLES",
    "NEVADA",
    "NEVIS/SAINT CHRISTOPHER/SAINT KITTS",
    "NEW BRUNSWICK",
    "NEW CALEDONIA",
    "NEW HAMPSHIRE",
    "NEW JERSEY",
    "NEW MEXICO",
    "NEW YORK",
    "NEW ZEALAND",
    "NEWFOUNDLAND",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NORFOLK ISLAND",
    "NORTH CAROLINA",
    "NORTH DAKOTA",
    "NORTH KOREA",
    "NORTH VIETNAM",
    "NORTHERN IRELAND",
    "NORTHWEST TERRITORIES",
    "NORWAY",
    "NOVA SCOTIA",
    "NUEVO LEON",
    "OAXACA",
    "OHIO",
    "OKINAWA",
    "OKLAHOMA",
    "OMAN",
    "ONTARIO",
    "OREGON",
    "OTHER NOT LISTED",
    "PAKISTAN",
    "PALAU, REPUBLIC OF",
    "PALMYRA ATOLL",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PARCEL ISLANDS",
    "PENNSYLVANIA",
    "PEOPLES REPUBLIC OF CHINA",
    "PERU",
    "PHILIPPINES",
    "PITCAIRN HENDERSON DUCIE OENO",
    "POLAND",
    "PORTUGAL",
    "PRINCE EDWARD ISLAND",
    "PUEBLA",
    "PUERTO RICO",
    "QATAR",
    "QUEBEC",
    "QUERETARO",
    "QUINTANA ROO",
    "REPUBLIC OF CONGO/BRAZZAVILLE",
    "REPUBLIC OF MACEDONIA",
    "REPUBLIC OF YEMEN",
    "REUNION",
    "RHODE ISLAND",
    "ROMANIA/RUMANIA",
    "RUSSIA (FORMERLY USSR)",
    "RUSSIAN FEDERATION",
    "RWANDA",
    "SAINT HELENA",
    "SAINT LUCIA",
    "SAINT PIERRE/MIGUELON",
    "SAINT VINCENT",
    "SAN LUIS POTOSI",
    "SAN MARINO",
    "SAO TOMER/PRINCIPE",
    "SASKATCHEWAN",
    "SAUDI ARABIA",
    "SCOTLAND",
    "SENEGAL",
    "SERBIA",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINALOA",
    "SINGAPORE",
    "SLOVAKIA",
    "SLOVENIA",
    "SOCIALIST REPUBLIC OF VIETNAM",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SONORA",
    "SOUTH AFRICA",
    "SOUTH CAROLINA",
    "SOUTH DAKOTA",
    "SOUTH GEORGIA & SOUTH SANDWICH ISLAN",
    "SOUTH KOREA",
    "SPAIN",
    "SPRATLY ISLANDS",
    "SRI LANKA (CEYLON)",
    "SUDAN",
    "SURINAM",
    "SVALBARD",
    "SWAZILAND",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIA",
    "TABASCO",
    "TAIWAN",
    "TAJIKISTAN",
    "TAMAULIPAS",
    "TANZANIA",
    "TENNESSEE",
    "TEXAS",
    "THAILAND",
    "TLAXCALA",
    "TOGO",
    "TOKELAU",
    "TONGA",
    "TONGAREVA ISLAND",
    "TRINIDAD/TOBAGO",
    "TROMELIN ISLAND",
    "TRUST TERRITORY OF PACIFIC ISLANDS",
    "TUAMOTU ARCHIPELAGO",
    "TUNISIA",
    "TURKEY",
    "TURKMENISTAN",
    "TURKS/CALCOS ISLANDS",
    "TUVALU",
    "UGANDA",
    "UKRAINE",
    "UNITED ARAB EMIRATES",
    "UNITED STATES OF AMERICA",
    "URUGUAY",
    "US VIRGIN ISLANDS",
    "UTAH",
    "UZBEKISTAN",
    "VANTUATU",
    "VATICAN CITY",
    "VENEZUELA",
    "VERACRUZ",
    "VERMONT",
    "VIRGINIA",
    "WAKE ISLAND",
    "WALES",
    "WALLIS AND FUTUNA",
    "WASHINGTON",
    "WEST BANK",
    "WEST GERMANY",
    "WEST INDIES",
    "WEST VIRGINIA",
    "WESTERN SAHARA",
    "WESTERN SAMOA",
    "WISCONSIN",
    "WYOMING",
    "YUCATAN",
    "YUGOSLAVIA",
    "YUKON TERRITORY",
    "ZACATECAS",
    "ZAIRE",
    "ZAMBIA",
    "ZIMBABWE",
  ],
};
