import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { ClerkProvider, SignInButton, SignOutButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { Button } from '@/components/ui/button'
import { dark } from '@clerk/themes';
import Link from "next/link";
import Header from "../app/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <div lang="en">
          <header className="flex items-center justify-between p-4">
            <SignedOut>
              <SignInButton><Button>Sign In</Button></SignInButton>
            </SignedOut>
            <SignedIn><UserButton /></SignedIn>
            <Header />
            <ModeToggle />
          </header>
          <main>{children}</main>
        </div>
      </ThemeProvider>
    </ClerkProvider>
  );
}